### ISSUE TITLE
'Recording' value for an event is inverted

### ISSUE THREAD

**Issue by 0xUnicorn** [Silverbaq/Bornhack-Schedule-Flutter#3]
https://github.com/Silverbaq/Bornhack-Schedule-Flutter/blob/c1f02e2e033f5ec0b2e23d820c9ce79c0534dba5/lib/ui/pages/event/event.page.dart#L95C53-L95C56

It seems to be enough to move around "Yes" and "No"

**Comment by Silverbaq** [comment]
It has been fixed for the updating coming for this years Bornhack
